### ISSUE TITLE
新入社員教育

### ISSUE THREAD

**Issue by JungSungHo** [JungSungHo/NODE-PYTHON-APP-TUTORIAL#1]
## Task
  - [x] Python入門講座[01:13:41]：https://www.youtube.com/watch?v=CPpRu_AJrW8
  - [x] Python超入門コース[01:14:14]：https://www.youtube.com/watch?v=HyU3XL2F9GE
  - [ ] この動画1本でゼロから基礎をマスター！【初心者向け】[01:18:20]：https://www.youtube.com/watch?v=kBKn5IkH06A
  - [ ] Q&A
